[build]
  command = "npm install && npm run build"
  publish = "build"
  functions = "server"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

[dev]
  command = "npm start"
  port = 3000
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://votre-backend-render.com/:splat"  # Remplacez par votre URL Render
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
